### ISSUE TITLE
Issue with 1.15.2 materialisation

### ISSUE THREAD

**Issue by Afroman77** [shedaniel/Materialisation#33]
when i hit a block with a materialization tool my game crashes

**Comment by Afroman77** [comment]
[23:43:38] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/mining/level/ToolManager
	at me.shedaniel.materialisation.MaterialisationUtils.mt_handleIsEffectiveOn(MaterialisationUtils.java:465) ~[Materialisation-Mod-Fabric-1.15.2.jar:?]
	at net.minecraft.class_1799.handler$zza000$isEffectiveOn(class_1799.java:1104) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_1799.method_7951(class_1799.java) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_1661.method_7383(class_1661.java:546) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_1657.method_7305(class_1657.java:813) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_2248.method_9594(class_2248.java:615) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_2680.method_11589(class_2680.java:249) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_3225.method_14263(class_3225.java:164) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_3244.method_12066(class_3244.java:912) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_2846.method_12361(class_2846.java:40) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_2846.method_11054(class_2846.java:10) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:33) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:173) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:743) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:138) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:135) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:725) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:719) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:151) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:704) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659) [intermediary-minecraft-1.15.2-client.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[23:43:38] [Server thread/ERROR]: This crash report has been saved to: C:\Users\afrom\Desktop\TRAAAADE GANG\Minecraft Servers\MultiMC\instances\fabric 1.15.2\.minecraft\crash-reports\crash-2020-04-24_23.43.38-server.txt
[23:43:38] [Server thread/INFO]: Stopping server
[23:43:38] [Server thread/INFO]: Saving players
[23:43:38] [main/FATAL]: Unreported exception thrown!
java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/mining/level/ToolManager
	at me.shedaniel.materialisation.MaterialisationUtils.mt_handleIsEffectiveOn(MaterialisationUtils.java:465) ~[Materialisation-Mod-Fabric-1.15.2.jar:?]
	at net.minecraft.class_1799.handler$zza000$isEffectiveOn(class_1799.java:1104) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_1799.method_7951(class_1799.java) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_1661.method_7383(class_1661.java:546) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_1657.method_7305(class_1657.java:813) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_2248.method_9594(class_2248.java:615) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_2680.method_11589(class_2680.java:249) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_636.method_2910(class_636.java:163) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.optifine.override.PlayerControllerOF.method_2910(PlayerControllerOF.java:51) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_310.method_1536(class_310.java:1307) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_310.method_1508(class_310.java:1595) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1445) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:964) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:619) [intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:204) [intermediary-minecraft-1.15.2-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.8.2+build.194.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.impl.mining.level.ToolManager
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_231]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161) ~[fabric-loader-0.8.2+build.194.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
	... 30 more
[23:43:38] [Server thread/INFO]: Afroman70 lost connection: Disconnected
[23:43:38] [Server thread/INFO]: Afroman70 left the game
[23:43:38] [Server thread/INFO]: Stopping singleplayer server as player logged out
[23:43:38] [Server thread/INFO]: Saving worlds
[23:43:38] [Server thread/INFO]: Saving chunks for level 'Trade Gang'/minecraft:overworld
[23:43:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (Trade Gang): All chunks are saved
[23:43:39] [Server thread/INFO]: Saving chunks for level 'Trade Gang'/minecraft:the_nether
[23:43:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[23:43:39] [Server thread/INFO]: Saving chunks for level 'Trade Gang'/minecraft:the_end
[23:43:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[23:43:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (Trade Gang): All chunks are saved
[23:43:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[23:43:39] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
---- Minecraft Crash Report ----
// There are four lights!

Time: 4/24/20 11:43 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/mining/level/ToolManager
	at me.shedaniel.materialisation.MaterialisationUtils.mt_handleIsEffectiveOn(MaterialisationUtils.java:465)
	at net.minecraft.class_1799.handler$zza000$isEffectiveOn(class_1799.java:1104)
	at net.minecraft.class_1799.method_7951(class_1799.java)
	at net.minecraft.class_1661.method_7383(class_1661.java:546)
	at net.minecraft.class_1657.method_7305(class_1657.java:813)
	at net.minecraft.class_2248.method_9594(class_2248.java:615)
	at net.minecraft.class_2680.method_11589(class_2680.java:249)
	at net.minecraft.class_636.method_2910(class_636.java:163)
	at net.optifine.override.PlayerControllerOF.method_2910(PlayerControllerOF.java:51)
	at net.minecraft.class_310.method_1536(class_310.java:1307)
	at net.minecraft.class_310.method_1508(class_310.java:1595)
	at net.minecraft.class_310.method_1574(class_310.java:1445)
	at net.minecraft.class_310.method_1523(class_310.java:964)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.impl.mining.level.ToolManager
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 30 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.shedaniel.materialisation.MaterialisationUtils.mt_handleIsEffectiveOn(MaterialisationUtils.java:465)
	at net.minecraft.class_1799.handler$zza000$isEffectiveOn(class_1799.java:1104)
	at net.minecraft.class_1799.method_7951(class_1799.java)
	at net.minecraft.class_1661.method_7383(class_1661.java:546)
	at net.minecraft.class_1657.method_7305(class_1657.java:813)
	at net.minecraft.class_2248.method_9594(class_2248.java:615)
	at net.minecraft.class_2680.method_11589(class_2680.java:249)
	at net.minecraft.class_636.method_2910(class_636.java:163)
	at net.optifine.override.PlayerControllerOF.method_2910(PlayerControllerOF.java:51)
	at net.minecraft.class_310.method_1536(class_310.java:1307)
	at net.minecraft.class_310.method_1508(class_310.java:1595)

-- Affected level --
Details:
	All players: 1 total; [class_746['Afroman70'/170, l='MpServer', x=-207.43, y=78.00, z=26.28]]
	Chunk stats: Client Chunk Cache: 2209, 1722
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: -3657615714119810274
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-128,63,0), Chunk: (at 0,3,0 in -8,0; contains blocks -128,0,0 to -113,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 14611 game time, 14611 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:611)
	at net.minecraft.class_310.method_1587(class_310.java:1921)
	at net.minecraft.class_310.method_1514(class_310.java:639)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
