### ISSUE TITLE
REI Breakage

### ISSUE THREAD

**Issue by zauberparacelsus** [shedaniel/Materialisation#43]
When this Materialization is run alongside REI, the latter does not function or appear, as if it weren't even installed.

Looking in the console, a large amount of error spew occurs when a world is loaded, related to the REI plugin for materialization:
```[14:17:12] [REI-SyncRecipes/INFO]: Reloading REI, registered 4 plugins: indrev:rei_plugin, roughlyenoughitems:default_runtime_plugin, materialisation:rei_plugin, roughlyenoughitems:default_plugin
[14:17:12] [main/INFO]: Loaded 3 advancements
[14:17:12] [REI-SyncRecipes/ERROR]: materialisation:rei_plugin plugin failed to register-displays!
java.lang.NoSuchMethodError: 'net.minecraft.class_3503 net.minecraft.class_3489.method_15106()'
	at me.shedaniel.materialisation.api.BetterIngredient.lambda$new$0(BetterIngredient.java:23) ~[Materialisation-3.0.2.jar:?]
	at net.minecraft.class_3528.method_15332(class_3528.java:16) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at me.shedaniel.materialisation.api.BetterIngredient.getStacks(BetterIngredient.java:89) ~[Materialisation-3.0.2.jar:?]
	at me.shedaniel.materialisation.api.BetterIngredient.getStacksList(BetterIngredient.java:93) ~[Materialisation-3.0.2.jar:?]
	at me.shedaniel.materialisation.rei.MaterialisationREIPlugin.lambda$registerRecipeDisplays$0(MaterialisationREIPlugin.java:48) ~[Materialisation-3.0.2.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:723) ~[?:?]
	at me.shedaniel.materialisation.rei.MaterialisationREIPlugin.lambda$registerRecipeDisplays$1(MaterialisationREIPlugin.java:47) ~[Materialisation-3.0.2.jar:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at me.shedaniel.materialisation.rei.MaterialisationREIPlugin.registerRecipeDisplays(MaterialisationREIPlugin.java:47) ~[Materialisation-3.0.2.jar:?]
	at me.shedaniel.rei.impl.RecipeHelperImpl.lambda$recipesLoaded$7(RecipeHelperImpl.java:395) ~[e0b556bb-ba1d-4ad7-8214-fb1e67aaa5e1.jar:?]
	at me.shedaniel.rei.impl.RecipeHelperImpl.pluginSection(RecipeHelperImpl.java:326) ~[e0b556bb-ba1d-4ad7-8214-fb1e67aaa5e1.jar:?]
	at me.shedaniel.rei.impl.RecipeHelperImpl.recipesLoaded(RecipeHelperImpl.java:395) ~[e0b556bb-ba1d-4ad7-8214-fb1e67aaa5e1.jar:?]
	at me.shedaniel.rei.impl.RecipeHelperImpl.tryRecipesLoaded(RecipeHelperImpl.java:336) ~[e0b556bb-ba1d-4ad7-8214-fb1e67aaa5e1.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore.lambda$syncRecipes$1(RoughlyEnoughItemsCore.java:240) ~[e0b556bb-ba1d-4ad7-8214-fb1e67aaa5e1.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[14:17:12] [REI-SyncRecipes/ERROR]: roughlyenoughitems:default_runtime_plugin plugin failed to register-displays!```

**Comment by shedaniel** [comment]
of course, materialisation is not updated to 1.16.2
